name: pluto_layout
description: PlutoLayout is a Flutter UI package that can configure a menu or tab screen on each side.
version: 1.0.0
homepage: https://pluto.weblaze.dev
repository: https://github.com/bosskmk/pluto_layout

environment:
  sdk: '>=3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.17.0
  rxdart: ^0.27.7
  flutter_riverpod: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
